\# IBM HR Employee Attrition — Notebook 1: Cleaning & EDA

\#\# Project Overview

This analysis explores a dataset of 1,470 IBM employees to understand
what factors are associated with employee attrition — when an employee
voluntarily leaves the company\.

Before drawing any conclusions, the first step is to verify the data
is complete, accurate, and ready for analysis\. This notebook documents
that quality check, mirroring \*\*Sections 1–2\*\* of the methodology report\.

In [3]:
# Import pandas so python can function similar to excel

import pandas as pd

# Bring in the pandas library
# "as pd" is a nickname — saves you typing "pandas" every time
# From here on, whenever you write pd, Python knows you mean pandas

In [5]:
# Load the CSV into a DataFrame

df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# pd.read_csv() opens the file
# and converts it into a table
# that Python can work with
# "df" is just a variable name — short for "DataFrame"
# A DataFrame is like a spreadsheet tab: rows, columns, headers
# You could name it anything (attrition, data, hr) — df is just convention

\#\# Section 1\.1 — Dataset Summary

The first question in any people analysis is: what are we working with?
We start by confirming the size of the dataset and the information
available on each employee\.

In [7]:
# Show the first 5 rows

df.head()

# Shows the first 5 rows of your DataFrame
# Like scrolling to the top of a spreadsheet to confirm it loaded right
# You're not changing anything — just looking

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [9]:
# Count rows and columns

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# df.shape returns a tuple: (number of rows, number of columns)
# .shape[0] is the row count, .shape[1] is the column count
# Confirms the dataset loaded as expected: 1,470 employees × 35 fields

Rows: 1470
Columns: 35


The dataset contains \*\*1,470 employees\*\* across \*\*35 variables\*\*,
including demographic information, job characteristics, compensation,
and satisfaction scores\. This is a complete snapshot — every row
represents one unique employee\.

\#\# Section 2\.1 — Data Quality Checks

We now run a series of validation checks before any analysis begins\.
Each check tests a different way the data could be wrong:

1\. Data types — are numbers stored as numbers and text as text?
2\. Categorical values — any typos or unexpected entries?
3\. Missing values — any empty cells?
4\. Duplicate IDs — does each row represent a unique employee?
5\. Age range — does anyone fall outside working age?
6\. Income validity — is anyone's income zero or negative?
7\. Impossible tenure — has anyone worked here longer than their full career?
8\. Constant columns — which fields have no variation?
9\. Performance rating range — are all rating values present?

In [11]:
# Confirm Python is reading each column correctly
# Numbers should be int64 or float64; text should be object

df.dtypes

# .dtypes returns the data type of every column
# int64 = whole number (Age, MonthlyIncome)
# object = text/string (Attrition, Department)
# we want this output to match what we'd expect for each column

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears   

In [13]:
# Inspect every text column for typos or unexpected values

cat_cols = ['Attrition', 'BusinessTravel', 'Department', 'EducationField',
            'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']

for col in cat_cols:
    print(f"\n{col}:", df[col].unique())

# .unique() returns every distinct value found in that column
# we loop through all 9 categorical columns and print them out
# this is how you catch issues like 'Sales' vs 'sales' vs 'Sales '
# we want clean, consistent values with no duplicates from typos


Attrition: ['Yes' 'No']

BusinessTravel: ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

Department: ['Sales' 'Research & Development' 'Human Resources']

EducationField: ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

Gender: ['Female' 'Male']

JobRole: ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

MaritalStatus: ['Single' 'Married' 'Divorced']

Over18: ['Y']

OverTime: ['Yes' 'No']


In [15]:
# Count nulls in every column

df.isnull().sum()

# df.isnull() returns True wherever a cell is empty
# .sum() counts the True values per column
# every column should return 0
# if anything's > 0, that column needs attention before analysis

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [17]:
# Each row should represent exactly one employee
# duplicate IDs would inflate headcount and skew attrition rates

dupe_count = df['EmployeeNumber'].duplicated().sum()
print("Duplicated Employee IDs:", dupe_count)

# .duplicated() flags each repeat after the first occurrence
# .sum() counts how many flags there are
# 0 means every Employee ID is unique

# Optional: surface the dupes if any exist
if dupe_count > 0:
    dupes = df[df['EmployeeNumber'].duplicated(keep=False)]
    print(dupes[['EmployeeNumber', 'Age', 'Department']])
else:
    print("No duplicates — clean.")

Duplicated Employee IDs: 0
No duplicates — clean.


In [19]:
# Anyone outside working age (18-65) is a likely data error

age_oor = df[(df['Age'] < 18) | (df['Age'] > 65)].shape[0]
print("Age out of range:", age_oor)

# df['Age'] < 18 — finds everyone under 18
# df['Age'] > 65 — finds everyone over 65
# | means OR — either condition flags the row
# .shape[0] counts how many rows matched
# 0 = no out-of-range ages

Age out of range: 0


In [21]:
# Nobody should have zero or negative monthly income

bad_income = df[df['MonthlyIncome'] <= 0].shape[0]
print("Negative or zero income:", bad_income)

# <= means "less than or equal to"
# 0 means every employee has a positive income value

Negative or zero income: 0


In [23]:
# An employee can't have worked at THIS company longer than their
# entire career — that would be logically impossible

impossible = df[df['YearsAtCompany'] > df['TotalWorkingYears']]
print("Impossible tenure rows:", impossible.shape[0])

# this compares two columns row by row
# Python checks each row: is YearsAtCompany > TotalWorkingYears?
# 0 means every record passes the logic check

Impossible tenure rows: 0


In [25]:
# Columns where every employee has the same value carry no
# predictive information — flag them so we can exclude later

print("StandardHours unique values:", df['StandardHours'].unique())
print("EmployeeCount unique values:", df['EmployeeCount'].unique())
print("Over18 unique values:        ", df['Over18'].unique())

# .unique() returns every distinct value in that column
# StandardHours = [80] for everyone
# EmployeeCount = [1] for everyone
# Over18 = ['Y'] for everyone
# all three will be excluded from any modeling — they have zero variance

StandardHours unique values: [80]
EmployeeCount unique values: [1]
Over18 unique values:         ['Y']


In [27]:
# Confirm what values exist in PerformanceRating
# this matters because if poor performers were rated and exited
# then "attrition" might include performance-managed exits

print("PerformanceRating unique values:", df['PerformanceRating'].unique())

# the scale is documented as 1-4 (1=Low to 4=Outstanding)
# but only values 3 and 4 appear in the data
# this supports the assumption that observed attrition is voluntary
# rather than performance-driven — there are no low ratings to begin with

PerformanceRating unique values: [3 4]


\#\#\# Data Quality Check Results

\| Check \| Result \| Action \|
\|\-\-\-\|\-\-\-\|\-\-\-\|
\| Data types \| ✅ All correct \| None \|
\| Categorical values \| ✅ All clean \| None \|
\| Missing values \| ✅ None found \| No imputation needed \|
\| Duplicate IDs \| ✅ None found \| All 1,470 records unique \|
\| Age range \| ✅ All 18\-60 \| None \|
\| Income validity \| ✅ All positive \| None \|
\| Impossible tenure \| ✅ None found \| None \|
\| Constant columns \| ⚠️ Identified \| Exclude \`StandardHours\`, \`EmployeeCount\`, \`Over18\` \|
\| PerformanceRating range \| ⚠️ Limited \(3\-4 only\) \| Supports voluntary\-attrition assumption \|

The dataset is clean and ready for analysis\.

\#\# Section 2\.2 — Target Variable Construction

The \`Attrition\` column is text \(\`'Yes'\` / \`'No'\`\)\. Before any modeling
or aggregation, we convert it to a binary numeric flag where
\`1 = left\` and \`0 = stayed\`\. This single conversion lets us:

\- Calculate attrition rate as a simple \`\.mean\(\)\`
\- Use the column directly as a target variable in modeling
\- Sum the column to get a count of departures

In [29]:
# Convert Attrition (text) to Attrition_Flag (binary 1/0)

df['Attrition_Flag'] = (df['Attrition'] == 'Yes').astype(int)

# (df['Attrition'] == 'Yes') returns True / False per row
# .astype(int) converts True → 1 and False → 0
# we keep the original Attrition column too — both are useful

# Confirm the conversion worked
print(df['Attrition_Flag'].value_counts())
print(f"\nOverall attrition rate: {df['Attrition_Flag'].mean()*100:.2f}%")

# value_counts() shows the count of 0s and 1s
# .mean() of a 0/1 column is the proportion of 1s — the attrition rate
# we expect roughly 16% based on the published dataset description

Attrition_Flag
0    1233
1     237
Name: count, dtype: int64

Overall attrition rate: 16.12%


The conversion produced \*\*237 leavers\*\* \(1\) and \*\*1,233 stayers\*\* \(0\),
for an overall attrition rate of \*\*16\.12%\*\*\. This 84/16 class imbalance
is a critical methodological consideration that will be addressed
in \*\*Notebook 4 \(Predictive Modeling\)\*\* through SMOTE and threshold
tuning, and through F1\-based scoring rather than accuracy\.

The dataset is now clean, validated, and ready for the descriptive
segmentation analysis in \*\*Notebook 2\*\*\.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=01782b8c-21ad-4a9f-9322-6be507743988' target="_blank">

Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>